files:
  - source: /lib/l10n/arb/app_en.arb
    translation: /lib/l10n/arb/app_%locale%.arb
    languages_mapping:
      locale:
        # Short codes for single-variant languages
        de: de
        es: es
        fr: fr
        hi: hi
        id: id
        ja: ja
        ko: ko
        nl: nl
        pt: pt
        ru: ru
        # Full codes for Chinese variants
        zh-CN: zh_CN
        zh-TW: zh_TW
