// GENERATED FILE - DO NOT EDIT
// Generated by: dart run tool/check_translations.dart 0
// Only languages with >= 0% translation completion are included.
// Translation is measured by comparing VALUES (not just key existence).
//
// To regenerate, run: dart run tool/check_translations.dart 0

import 'package:flutter/widgets.dart';

/// Minimum translation completion threshold used to filter languages.
const int translationThreshold = 0;

/// List of locales that meet the translation threshold.
/// Only these languages will be available in the app.
const List<Locale> filteredSupportedLocales = <Locale>[
  Locale('en'),
  Locale('ru'),
  Locale('id'),
  Locale('ja'),
  Locale('de'),
  Locale('es'),
  Locale('fr'),
  Locale('hi'),
  Locale('ko'),
  Locale('nl'),
  Locale('pt'),
  Locale('zh'),
  Locale('zh', 'CN'),
  Locale('zh', 'TW'),
];

/// Set of locale codes for quick lookup.
const Set<String> filteredLocaleCodes = <String>{
  'en',
  'ru',
  'id',
  'ja',
  'de',
  'es',
  'fr',
  'hi',
  'ko',
  'nl',
  'pt',
  'zh',
  'zh_CN',
  'zh_TW',
};
